Repository UN-OCHA/hpc-api, pull requests merged in 2021-12, with the labels that each got.

#39 Update dependencies
  .husky/pre-commit
  package.json
  src/domain-services/location/location-service.ts
  src/domain-services/plans/plan-service.ts
  yarn.lock
Labels: ready for review

#40 ✨ OPS-7910: Introduce new logging system using bunyan
  config/index.ts
  docker-compose.integrated.yml
  docker-compose.yml
  package.json
  src/common-libs/logging/context.ts
  src/common-libs/logging/data.ts
  src/common-libs/logging/index.ts
  src/common-libs/logging/printing.ts
  src/server.ts
  yarn.lock
Labels: ready for review, needs testing

#41 📦️ Prepare release `v0.0.2` and deploy to stage
  .husky/pre-commit
  config/index.ts
  docker-compose.integrated.yml
  docker-compose.yml
  package.json
  src/common-libs/logging/context.ts
  src/common-libs/logging/data.ts
  src/common-libs/logging/index.ts
  src/common-libs/logging/printing.ts
  src/domain-services/location/location-service.ts
  src/domain-services/plans/plan-service.ts
  src/server.ts
  yarn.lock
Labels: deployment, deploy to red.dev

#45 Update develop with changes from env/stage
  package.json
Labels: mergeback

#44 📦️ Release `v0.0.2` and deploy to production
  .husky/pre-commit
  config/index.ts
  docker-compose.integrated.yml
  docker-compose.yml
  package.json
  src/common-libs/logging/context.ts
  src/common-libs/logging/data.ts
  src/common-libs/logging/index.ts
  src/common-libs/logging/printing.ts
  src/domain-services/location/location-service.ts
  src/domain-services/plans/plan-service.ts
  src/server.ts
  yarn.lock
Labels: deployment

#48 ✨ OPS-7910: Various improvements to logging
  config/index.ts
  package.json
  src/common-libs/logging/data.ts
  src/common-libs/logging/index.ts
  yarn.lock
Labels: deploy to red.dev, ready for review

#50 ✨ OPS-7912: Enable NewRelic
  src/server.ts
Labels: deploy to red.dev, ready for review

#51 📦️ Prepare release `v0.0.3` and deploy to stage
  config/index.ts
  package.json
  src/common-libs/logging/data.ts
  src/common-libs/logging/index.ts
  src/server.ts
  yarn.lock
Labels: deployment

#52 Update develop with changes from env/stage
  package.json
Labels: mergeback

#53 🚀 Release `v0.0.3` and deploy to prod
  config/index.ts
  package.json
  src/common-libs/logging/data.ts
  src/common-libs/logging/index.ts
  src/server.ts
  yarn.lock
Labels: deployment
