Repository UN-OCHA/hpc-api, pull requests merged in 2021-11, with the labels that each got.

#31 Update `strip-ansi` sub-dependency
  yarn.lock
Labels: dependencies, ready for review

#21 HPC-7904: 🛂 Setup authentication for resolvers
  .husky/.gitignore
  bin/install.sh
  bin/port-forward.js
  config/index.ts
  docker-compose.integrated.yml
  docs/AUTH.md
  env/api/node.sh
  package.json
  src/common-libs/auth/index.ts
  src/common-libs/auth/permission-decorator.ts
  src/data-providers/postgres/index.ts
  src/data-providers/postgres/knex-types.ts
  src/data-providers/postgres/models/auth/auth-grant.ts
  src/data-providers/postgres/models/auth/auth-grantLog.ts
  src/data-providers/postgres/models/auth/auth-grantee.ts
  src/data-providers/postgres/models/auth/auth-invite.ts
  src/data-providers/postgres/models/auth/auth-target.ts
  src/data-providers/postgres/models/auth/auth-token.ts
  src/data-providers/postgres/models/auth/index.ts
  src/data-providers/postgres/models/common/base.ts
  src/data-providers/postgres/models/index.ts
  src/data-providers/postgres/models/location.ts
  src/data-providers/postgres/models/participant.ts
  src/data-providers/postgres/models/plans/plan.ts
  src/data-providers/postgres/models/year.ts
  src/domain-services/Context.ts
  src/domain-services/location/graphql/resolver.ts
  src/domain-services/location/location-service.ts
  src/domain-services/plans/plan-service.ts
  src/server.ts
  tsconfig.json
  yarn.lock
Labels: ready for review

#35 Update develop with changes from env/stage
  .eslintignore
  .github/CODEOWNERS
  .github/workflow.config.json
  .github/workflows/workflow.yml
  Dockerfile
  bin/install.sh
  docker-compose.integrated.yml
  docker-compose.yml
  package.json
  src/register-ts-node.js
  start.js
  start_node
  tsconfig.json
  yarn.lock
Labels: mergeback

#38 ⬆️ Update `@unocha/hpc-repo-tools` to `v0.2.2`
  package.json
  yarn.lock
Labels: ready for review
