Repository UN-OCHA/hpc-api, pull requests merged in 2022-02, with the labels that each got.

#59 :whale: Use `16-alpine` tag for `nodejs` image
  env/api/Dockerfile
Labels: ready for review

#60 📦️ Prepare release `v0.1.0` and deploy to stage
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  .npmrc
  CONTRIBUTING.md
  Dockerfile
  env/api/Dockerfile
  package.json
  yarn.lock
Labels: deployment

#62 🚀 Release `v0.1.0` and deploy to production
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  .npmrc
  CONTRIBUTING.md
  Dockerfile
  env/api/Dockerfile
  package.json
  yarn.lock
Labels: deployment

#58 Don't enable New Relic in local development
  docker-compose.integrated.yml
  docker-compose.yml
Labels: ready for review

#66 Update develop with changes from env/stage
  package.json
Labels: mergeback
