Repository UN-OCHA/hpc-api, pull requests merged in 2022-05, with the labels that each got.

#88 Bump `moment` from 2.29.1 to 2.29.3
  yarn.lock
Labels: dependencies, ready for review

#89 📦️ Prepare release `v4.2.2` and deploy to stage
  package.json
  yarn.lock
Labels: deployment, ready for review

#90 Update develop with changes from env/stage
  package.json
Labels: mergeback
