Repository UN-OCHA/hpc-api, pull requests merged in 2022-06, with the labels that each got.

#95 Use branding from `hpc-api-core`
  src/common-utils/branding.ts
  src/domain-services/location/graphql/types.ts
  src/domain-services/plans/graphql/types.ts
Labels: ready for review

#96 :package: Prepare release `v4.2.3` and deploy to stage
  package.json
  src/common-utils/branding.ts
  src/domain-services/location/graphql/types.ts
  src/domain-services/plans/graphql/types.ts
Labels: deployment

#98 :rocket: Release `v4.2.3` and deploy to production
  package.json
  src/common-utils/branding.ts
  src/domain-services/location/graphql/types.ts
  src/domain-services/plans/graphql/types.ts
Labels: deployment

#97 Update develop with changes from env/stage
  package.json
Labels: mergeback
