Repository UN-OCHA/hpc-api, pull requests merged in 2022-03, with the labels that each got.

#67 Set ES2021 as Typescript compilation target
  package.json
  tsconfig.json
  yarn.lock
Labels: ready for review

#75 :package: Prepare release `v4.2.0` and deploy to stage
  package.json
  tsconfig.json
  yarn.lock
Labels: deployment

#76 Update develop with changes from env/stage
  package.json
Labels: mergeback

#77 :rocket: Release `v4.2.0` and deploy to production
  package.json
  tsconfig.json
  yarn.lock
Labels: deployment

#81 Update dependencies
  package.json
  yarn.lock
Labels: ready for review

#82 📦️ Prepare release `v4.2.1` and deploy to stage
  package.json
  yarn.lock
Labels: deployment

#83 Update develop with changes from env/stage
  package.json
Labels: mergeback

#84 🚀 Release `v4.2.1` and deploy to production
  package.json
  yarn.lock
Labels: deployment
