Repository UN-OCHA/hpc-api, pull requests merged in 2023-09, with the labels that each got.

#205 HPC-8663: add software info query
  src/domain-services/software-info/graphql/resolver.ts
  src/domain-services/software-info/graphql/types.ts
  src/domain-services/software-info/software-info-service.ts
Labels: ready for review

#206 📦️ Prepare release `v4.5.0` and deploy to stage
  package.json
  src/domain-services/software-info/graphql/resolver.ts
  src/domain-services/software-info/graphql/types.ts
  src/domain-services/software-info/software-info-service.ts
  yarn.lock
Labels: deployment

#208 🚀 Release `v4.5.0` and deploy to production
  package.json
  src/domain-services/software-info/graphql/resolver.ts
  src/domain-services/software-info/graphql/types.ts
  src/domain-services/software-info/software-info-service.ts
  yarn.lock
Labels: deployment

#212 📦️ Prepare release `v4.5.1` and deploy to stage
  package.json
  yarn.lock
Labels: deployment

#213 Update develop with changes from env/stage
  package.json
Labels: mergeback

#214 🚀 Release `v4.5.1` and deploy to production
  package.json
  yarn.lock
Labels: deployment
