Repository UN-OCHA/hpc-api, pull requests merged in 2024-01, with the labels that each got.

#232 📦️ Prepare release `v4.6.2` and deploy to stage
  package.json
  yarn.lock
Labels: deployment

#233 Update develop with changes from env/stage
  package.json
Labels: mergeback

#235 🚀 Release `v4.6.2` and deploy to production
  package.json
  yarn.lock
Labels: deployment

#234 Update CodeQL Action to v3
  .github/workflows/codeql-analysis.yml
Labels: ready for merge
