Repository UN-OCHA/hpc-api, pull requests merged in 2024-03, with the labels that each got.

#217 HPC-7811 set up test environment
  .github/workflows/ci.yml
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  bin/test.sh
  jest.config.ts
  package.json
  src/data-providers/postgres/index.ts
  src/server.ts
  tests/compose.yaml
  tests/migration/schema-2024-03-13.sql
  tests/resolvers/software-info.spec.ts
  tests/test-environment-setup.ts
  tests/test-environment.spec.ts
  tests/testContext.ts
  tests/utils/connection.ts
  tests/utils/server.ts
  tsconfig.json
  yarn.lock
Labels: ready for review

#245 📦️ Prepare release v4.6.4 and deploy to stage
  .github/workflows/ci.yml
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  bin/test.sh
  jest.config.ts
  package.json
  src/data-providers/postgres/index.ts
  src/server.ts
  tests/compose.yaml
  tests/migration/schema-2024-03-13.sql
  tests/resolvers/software-info.spec.ts
  tests/test-environment-setup.ts
  tests/test-environment.spec.ts
  tests/testContext.ts
  tests/utils/connection.ts
  tests/utils/server.ts
  tsconfig.json
  yarn.lock
Labels: deployment

#246 Update develop with changes from env/stage
  package.json
Labels: mergeback

#247 🚀 Release v4.6.4 and deploy to production
  .github/workflows/ci.yml
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  bin/test.sh
  jest.config.ts
  package.json
  src/data-providers/postgres/index.ts
  src/server.ts
  tests/compose.yaml
  tests/migration/schema-2024-03-13.sql
  tests/resolvers/software-info.spec.ts
  tests/test-environment-setup.ts
  tests/test-environment.spec.ts
  tests/testContext.ts
  tests/utils/connection.ts
  tests/utils/server.ts
  tsconfig.json
  yarn.lock
Labels: deployment
