Repository UN-OCHA/hpc-api, pull requests merged in 2024-12, with the labels that each got.

#219 HPC-8569 flow list resolver
  src/domain-services/base-types.ts
  src/domain-services/categories/category-service.ts
  src/domain-services/categories/graphql/types.ts
  src/domain-services/categories/model.ts
  src/domain-services/external-reference/external-reference-service.ts
  src/domain-services/flow-link/flow-link-service.ts
  src/domain-services/flow-object/flow-object-service.ts
  src/domain-services/flow-object/model.ts
  src/domain-services/flow-object/utils.ts
  src/domain-services/flows/flow-search-service.ts
  src/domain-services/flows/flow-service.ts
  src/domain-services/flows/graphql/args.ts
  src/domain-services/flows/graphql/resolver.ts
  src/domain-services/flows/graphql/types.ts
  src/domain-services/flows/model.ts
  src/domain-services/flows/strategy/flow-search-strategy.ts
  src/domain-services/flows/strategy/flowID-search-strategy.ts
  src/domain-services/flows/strategy/impl/get-flowIds-flow-category-conditions-strategy-impl.ts
  src/domain-services/flows/strategy/impl/get-flowIds-flow-from-nested-flow-filters-strategy-impl.ts
  src/domain-services/flows/strategy/impl/get-flowIds-flow-object-conditions-strategy-impl.ts
  src/domain-services/flows/strategy/impl/only-flow-conditions-strategy-impl.ts
  src/domain-services/flows/strategy/impl/search-flow-by-filters-strategy-impl.ts
  src/domain-services/flows/strategy/impl/utils.ts
  src/domain-services/legacy/legacy-service.ts
  src/domain-services/location/graphql/types.ts
  src/domain-services/location/location-service.ts
  src/domain-services/organizations/graphql/types.ts
  src/domain-services/organizations/organization-service.ts
  src/domain-services/plans/graphql/types.ts
  src/domain-services/plans/plan-service.ts
  src/domain-services/report-details/graphql/types.ts
  src/domain-services/report-details/report-detail-service.ts
  src/domain-services/usage-years/graphql/types.ts
  src/domain-services/usage-years/usage-year-service.ts
  src/utils/database-types.ts
  src/utils/graphql/pagination.ts
  tests/resolvers/flows.spec.ts
  tests/resolvers/software-info.spec.ts
  tests/services/flow-search-service.spec.ts
  tests/services/flow-service.spec.ts
  tests/utils/connection.ts
Labels: needs rebase, ready for merge

#304 📦️ Prepare release `v4.8.0` and deploy to stage
  package.json
  src/domain-services/base-types.ts
  src/domain-services/categories/category-service.ts
  src/domain-services/categories/graphql/types.ts
  src/domain-services/categories/model.ts
  src/domain-services/external-reference/external-reference-service.ts
  src/domain-services/flow-link/flow-link-service.ts
  src/domain-services/flow-object/flow-object-service.ts
  src/domain-services/flow-object/model.ts
  src/domain-services/flow-object/utils.ts
  src/domain-services/flows/flow-search-service.ts
  src/domain-services/flows/flow-service.ts
  src/domain-services/flows/graphql/args.ts
  src/domain-services/flows/graphql/resolver.ts
  src/domain-services/flows/graphql/types.ts
  src/domain-services/flows/model.ts
  src/domain-services/flows/strategy/flow-search-strategy.ts
  src/domain-services/flows/strategy/flowID-search-strategy.ts
  src/domain-services/flows/strategy/impl/get-flowIds-flow-category-conditions-strategy-impl.ts
  src/domain-services/flows/strategy/impl/get-flowIds-flow-from-nested-flow-filters-strategy-impl.ts
  src/domain-services/flows/strategy/impl/get-flowIds-flow-object-conditions-strategy-impl.ts
  src/domain-services/flows/strategy/impl/only-flow-conditions-strategy-impl.ts
  src/domain-services/flows/strategy/impl/search-flow-by-filters-strategy-impl.ts
  src/domain-services/flows/strategy/impl/utils.ts
  src/domain-services/legacy/legacy-service.ts
  src/domain-services/location/graphql/types.ts
  src/domain-services/location/location-service.ts
  src/domain-services/organizations/graphql/types.ts
  src/domain-services/organizations/organization-service.ts
  src/domain-services/plans/graphql/types.ts
  src/domain-services/plans/plan-service.ts
  src/domain-services/report-details/graphql/types.ts
  src/domain-services/report-details/report-detail-service.ts
  src/domain-services/usage-years/graphql/types.ts
  src/domain-services/usage-years/usage-year-service.ts
  src/utils/database-types.ts
  src/utils/graphql/pagination.ts
  tests/resolvers/flows.spec.ts
  tests/resolvers/software-info.spec.ts
  tests/services/flow-search-service.spec.ts
  tests/services/flow-service.spec.ts
  tests/utils/connection.ts
  yarn.lock
Labels: deployment

#305 Update develop with changes from env/stage
  package.json
Labels: mergeback

#306 🚀 Release `v4.8.0` and deploy to production
  package.json
  src/domain-services/base-types.ts
  src/domain-services/categories/category-service.ts
  src/domain-services/categories/graphql/types.ts
  src/domain-services/categories/model.ts
  src/domain-services/external-reference/external-reference-service.ts
  src/domain-services/flow-link/flow-link-service.ts
  src/domain-services/flow-object/flow-object-service.ts
  src/domain-services/flow-object/model.ts
  src/domain-services/flow-object/utils.ts
  src/domain-services/flows/flow-search-service.ts
  src/domain-services/flows/flow-service.ts
  src/domain-services/flows/graphql/args.ts
  src/domain-services/flows/graphql/resolver.ts
  src/domain-services/flows/graphql/types.ts
  src/domain-services/flows/model.ts
  src/domain-services/flows/strategy/flow-search-strategy.ts
  src/domain-services/flows/strategy/flowID-search-strategy.ts
  src/domain-services/flows/strategy/impl/get-flowIds-flow-category-conditions-strategy-impl.ts
  src/domain-services/flows/strategy/impl/get-flowIds-flow-from-nested-flow-filters-strategy-impl.ts
  src/domain-services/flows/strategy/impl/get-flowIds-flow-object-conditions-strategy-impl.ts
  src/domain-services/flows/strategy/impl/only-flow-conditions-strategy-impl.ts
  src/domain-services/flows/strategy/impl/search-flow-by-filters-strategy-impl.ts
  src/domain-services/flows/strategy/impl/utils.ts
  src/domain-services/legacy/legacy-service.ts
  src/domain-services/location/graphql/types.ts
  src/domain-services/location/location-service.ts
  src/domain-services/organizations/graphql/types.ts
  src/domain-services/organizations/organization-service.ts
  src/domain-services/plans/graphql/types.ts
  src/domain-services/plans/plan-service.ts
  src/domain-services/report-details/graphql/types.ts
  src/domain-services/report-details/report-detail-service.ts
  src/domain-services/usage-years/graphql/types.ts
  src/domain-services/usage-years/usage-year-service.ts
  src/utils/database-types.ts
  src/utils/graphql/pagination.ts
  tests/resolvers/flows.spec.ts
  tests/resolvers/software-info.spec.ts
  tests/services/flow-search-service.spec.ts
  tests/services/flow-service.spec.ts
  tests/utils/connection.ts
  yarn.lock
Labels: deployment
