Repository UN-OCHA/hpc-api, pull requests merged in 2024-05, with the labels that each got.

#250 HPC-9551: Chunk model version's bulk update
  config/index.ts
  src/common-libs/plan/versioning.ts
Labels: deploy to red.dev, needs minor changes

#251 📦️ Prepare release v4.6.5 and deploy to stage
  config/index.ts
  package.json
  src/common-libs/plan/versioning.ts
Labels: deployment

#252 Update develop with changes from env/stage
  package.json
Labels: mergeback
