Repository UN-OCHA/hpc-api, pull requests merged in 2025-05, with the labels that each got.

#362 Update `@unocha/hpc-repo-tools` to `v6.4.0`
  .git-blame-ignore-revs
  .github/CODEOWNERS
  .prettierignore
  Dockerfile
  bin/install.sh
  bin/sync-db.sh
  bin/test.sh
  env/api/Dockerfile
  package.json
  prettier.config.mjs
  src/common-libs/auth/index.ts
  src/domain-services/external-reference/external-reference-service.ts
  src/domain-services/flows/flow-search-service.ts
  src/domain-services/plans/plan-service.ts
  yarn.lock
Labels: ready for merge

#363 HPC-9905: Upgrade to Node.js v22
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  Dockerfile
  env/api/Dockerfile
  package.json
  tsconfig.json
  yarn.lock
Labels: ready for merge

#370 📦 Prepare release `v4.9.0` and deploy to stage
  .git-blame-ignore-revs
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  .prettierignore
  Dockerfile
  bin/install.sh
  bin/sync-db.sh
  bin/test.sh
  compose.integrated.yaml
  compose.yaml
  env/api/Dockerfile
  package.json
  prettier.config.mjs
  src/common-libs/auth/index.ts
  src/domain-services/external-reference/external-reference-service.ts
  src/domain-services/flows/flow-search-service.ts
  src/domain-services/plans/plan-service.ts
  tests/compose.yaml
  tsconfig.json
  yarn.lock
Labels: deployment

#371 Update develop with changes from env/stage
  package.json
Labels: mergeback

#372 🚀 Release `v4.9.0` and deploy to production
  .git-blame-ignore-revs
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  .prettierignore
  Dockerfile
  bin/install.sh
  bin/sync-db.sh
  bin/test.sh
  compose.integrated.yaml
  compose.yaml
  env/api/Dockerfile
  package.json
  prettier.config.mjs
  src/common-libs/auth/index.ts
  src/domain-services/external-reference/external-reference-service.ts
  src/domain-services/flows/flow-search-service.ts
  src/domain-services/plans/plan-service.ts
  tests/compose.yaml
  tsconfig.json
  yarn.lock
Labels: deployment

#369 Update Dependabot config
  .github/dependabot.yml
Labels: ready for merge

#385 Update develop with changes from env/stage
  package.json
Labels: mergeback

#383 Update `@unocha/hpc-repo-tools` to `v7.1.0`
  .git-blame-ignore-revs
  Dockerfile
  package.json
  yarn.lock
Labels: dependencies, ready for review

#386 Update release `v4.9.1` with changes from `develop` and deploy to stage
  .git-blame-ignore-revs
  Dockerfile
  package.json
  yarn.lock
Labels: deployment

#389 🚀 Release `v4.9.1` and deploy to production
  .git-blame-ignore-revs
  .github/dependabot.yml
  Dockerfile
  package.json
  src/domain-services/categories/category-service.ts
  src/domain-services/categories/graphql/types.ts
  tests/resolvers/flows.spec.ts
  yarn.lock
Labels: deployment

#392 📦 Prepare release `v4.9.2` and deploy to stage
  package.json
  src/domain-services/flow-link/flow-link-service.ts
  src/domain-services/flows/flow-search-service.ts
  src/domain-services/flows/flow-service.ts
Labels: deployment
